<?php
/**
 * +----------------------------------------------------------------------
 * |
 * +----------------------------------------------------------------------
 * | Author: lidong <947714443@qq.com>
 * +----------------------------------------------------------------------
 * | Date 2019/9/22 0022
 * +----------------------------------------------------------------------
 * | File Describe:基础继承模型
 */
namespace base\mybase\model;

use think\Model;

/**
 * Describe:
 * Class Mybase
 *
 * @package base\mybase\model
 * @author  lidong<947714443@qq.com>
 * @date    2019/9/22 0022
 */
class Mybase extends Model {

    /**
     * Describe:
     *
     * @author lidong<947714443@qq.com>
     * @date   2019/9/22 0022
     */
    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        // $name = substr(__CLASS__,'','');
        // $this->table = $name;
        // $this->name = '';
    }


}