<?php
/**
 * +----------------------------------------------------------------------
 * |
 * +----------------------------------------------------------------------
 * | Author: lidong <947714443@qq.com>
 * +----------------------------------------------------------------------
 * | Date 2019/9/22 0022
 * +----------------------------------------------------------------------
 * | File Describe:基础继承控制器
 */
namespace base\mybase\controller;

use base\mybase\logic\MybaseLogic;
use think\captcha\Captcha;
use think\Controller;

/**
 * Describe:
 * Class Mybase
 *
 * @package base\mybase\controller
 * @author  lidong<947714443@qq.com>
 * @date    2019/9/22 0022
 */
class Mybase extends Controller {

    /**
     * Describe:主要操作逻辑类
     *
     * @var \base\mybase\logic\MybaseLogic
     */
    protected $logic;

    /**
     * Describe:每页显示条数
     *
     * @var int
     */
    protected $limit = 15;

    /**
     * 是否允许修改
     */
    protected $is_allow_edit = true;

    /**
     * 是否允许添加
     *
     * @var string
     */
    protected $is_allow_add = true;

    /**
     * 是否允许删除(标记删除)
     *
     * @var string
     */
    protected $is_allow_del = true;

    /**
     * 是否允许启用
     *
     * @var string
     */
    protected $is_allow_enable = true;

    /**
     * 是否允许禁用
     *
     * @var string
     */
    protected $is_allow_disable = true;

    /**
     * 是否允许删除(真实删除)
     *
     * @var string
     */
    protected $is_allow_delete = false;


    /**
     * Describe:初始化方法
     *
     * @author lidong<947714443@qq.com>
     * @date   2019/10/16 0016
     */
    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->logic = new MybaseLogic();
    }


    /**
     * Describe:首页/列表页默认展示
     *
     * @return mixed
     * @author lidong<947714443@qq.com>
     * @date   2019/10/16 0016
     */
    public function index() {
        return $this->fetch();
    }


    /**
     * Describe:添加页默认展示
     *
     * @return mixed
     * @author lidong<947714443@qq.com>
     * @date   2019/10/16 0016
     */
    public function add() {
        return $this->fetch();
    }


    /**
     * Describe:编辑页默认展示
     *
     * @author lidong<947714443@qq.com>
     * @date   2019/10/16 0016
     */
    public function edit() {
        return $this->fetch();
    }


    /**
     * Describe:禁用
     *
     * @author lidong<947714443@qq.com>
     * @date   2019/10/16 0016
     */
    public function disable() {
        if (!$this->request->isPost()) { /*TODO:错误提示*/
        }
        /*TODO:数据更新操作*/
    }


    /**
     * Describe:ajax切换验证码请求
     *
     * @return \think\response\Json
     * @author lidong<947714443@qq.com>
     * @date   2019/10/22 0022
     */
    public function change_captcha() {
        $captcha_id = $this->request->param('captcha', '', 'trim');
        $params = ['version' => rand()];
        if (!empty($captcha_id)) {
            $params['captcha_id'] = $captcha_id;
        }
        $url = url('captcha', $params, true, true);
        return json(['code' => 1, 'url' => $url]);
    }


    /**
     * Describe:输出图片验证码
     *
     * @return \think\Response
     * @author lidong<947714443@qq.com>
     * @date   2019/10/22 0022
     */
    public function captcha() {
        $config = [
            /* 默认验证码配置*/
            'fontSize' => '20',
            'imageH'   => '38',
            'imageW'   => '170',
            'length'   => '5',
            'bg'       => [200, 200, 200],
        ];
        $font_size = $this->request->param('font_size', 0, 'intval');
        if ($font_size > 0 && $font_size < 100) { /* 设置验证码字号 */
            $config['fontSize'] = $font_size;
        }
        $height = $this->request->param('height', 0, 'intval');
        if ($height > 0 && $height < 100) { /* 设置验证码图片高度 */
            $config['imageH'] = $height;
        }
        $width = $this->request->param('width', 0, 'intval');
        if ($width > 0 && $width < 200) { /* 设置验证码图片宽度 */
            $config['imageW'] = $width;
        }
        $len = $this->request->param('len', 0, 'intval');
        if ($len > 0 && $len <= 20) { /* 设置验证码长度 */
            $config['length'] = $len;
        }
        $bg = $this->request->param('bg', '', 'trim');
        if (!empty($bg)) {
            $bg_arr = explode(',', $bg);
            array_walk($bg_arr, 'intval');
            if (count($bg_arr) >= 3 && $bg_arr[0] <= 255 && $bg_arr[1] <= 255 && $bg_arr[2] <= 255) {
                $config['bg'] = $bg_arr;
            }
        }
        $id = $this->request->param('captcha_id', '1', 'trim');
        $Captcha = new Captcha($config);
        return $Captcha->entry($id);
    }


    /**
     * Describe:图片验证码验证
     *
     * @param string $value 需要验证的验证码
     * @param string $id    验证码ID
     *
     * @return bool
     * @author lidong<947714443@qq.com>
     * @date   2019/10/22 0022
     */
    public function captcha_check($value = '', $id = '1') {
        $Captcha = new Captcha();
        return $Captcha->check($value, $id);
    }


}