<?php
/**
 * +----------------------------------------------------------------------
 * |
 * +----------------------------------------------------------------------
 * | Author: lidong <947714443@qq.com>
 * +----------------------------------------------------------------------
 * | Date 2019/9/22 0022
 * +----------------------------------------------------------------------
 * | File Describe:基础继承控制器
 */
namespace base\mybase\controller;

use base\mybase\logic\MybaseLogic;
use think\Controller;

/**
 * Describe:
 * Class Mybase
 *
 * @package base\mybase\controller
 * @author  lidong<947714443@qq.com>
 * @date    2019/9/22 0022
 */
class Mybase extends Controller {

    /**
     * Describe:主要操作逻辑类
     *
     * @var \base\mybase\logic\MybaseLogic
     */
    protected $logic;


    /**
     * Describe:初始化方法
     *
     * @author lidong<947714443@qq.com>
     * @date   2019/10/16 0016
     */
    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->logic = new MybaseLogic();
    }


    public function index() {
        return $this->fetch();
    }


}