<?php
/**
 * +----------------------------------------------------------------------
 * |
 * +----------------------------------------------------------------------
 * | Author: lidong <947714443@qq.com>
 * +----------------------------------------------------------------------
 * | Date 2019/9/21 0021
 * +----------------------------------------------------------------------
 * | File Describe:
 */
namespace app\common\model;

use think\Model;

/**
 * Describe:
 * Class MybaseModel
 *
 * @package app\common\model
 * @author  lidong<947714443@qq.com>
 * @date    2019/9/21 0021
 */
class Mybase extends Model {

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        // $name = substr(__CLASS__,'','');
        // $this->table = $name;
        // $this->name = '';
    }


}