<?php
/**
 * +----------------------------------------------------------------------
 * |
 * +----------------------------------------------------------------------
 * | Author: lidong <947714443@qq.com>
 * +----------------------------------------------------------------------
 * | Date 2019/10/21 0021
 * +----------------------------------------------------------------------
 * | File Describe:
 */
namespace base\mybase\logic;

use base\mybase\model\Admin as AdminModel;
use base\mybase\validate\Admin as AdminValidate;
use plugins\tools\StrPro;

/**
 * Describe:
 * Class AdminLogic
 *
 * @package base\mybase\logic
 * @author  lidong<947714443@qq.com>
 * @date    2019/10/21 0021
 */
class AdminLogic extends MybaseLogic {

    /**
     * Describe:主要操作模型
     *
     * @var \base\mybase\model\Admin
     */
    protected $model;

    /**
     * Describe:主要使用验证器
     *
     * @var \base\mybase\validate\Admin
     */
    protected $validate;

    /**
     * Describe:管理员信息
     *
     * @var array
     */
    protected $admin = null;

    /**
     * Describe:管理员ID
     *
     * @var int
     */
    protected $admin_id = 0;


    /**
     * Describe:初始化，指定操作模型和验证器
     *
     * @author lidong<947714443@qq.com>
     * @date   2019/10/22 0022
     */
    public function _init() {
        parent::_init(); // TODO: Change the autogenerated stub
        $this->model = new AdminModel();
        $this->validate = new AdminValidate();
    }


    /**
     * Describe:管理员登录[登录名称唯一]
     *
     * @param string $username 登录名[唯一]
     * @param string $password 登录密码[明码]
     *
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @return bool
     * @author lidong<947714443@qq.com>
     * @date   2019/10/22 0022
     */
    public function do_login_username_unique($username = '', $password = '') {
        if (empty($username)) {
            $this->error = '请填写账号';
            return false;
        }
        if (empty($password)) {
            $this->error = '请填写密码';
            return false;
        }
        $map = [];
        $map[] = [$this->model->field_username, 'eq', $username];
        $map[] = [$this->model->field_disable, 'in', [0, 1]];
        $admin = $this->model->where($map)->find();
        if (empty($admin)) {
            $this->error = '用户不存在';
            return false;
        }
        if (StrPro::password_encrypt($password, $admin[$this->model->field_salt]) != $admin[$this->model->field_password]) {
            $this->error = '用户名或密码错误';
            return false;
        }
        $this->admin = $admin;
        $this->admin_id = $admin_id = $admin[$this->model->getPk()];
        set_admin($admin);
        set_admin_id($admin_id);
        /* TODO:登录操作记录 */
        return true;
    }


    /**
     * Describe:
     *
     * @author lidong<947714443@qq.com>
     * @date   2019/10/23 0023
     */
    public function logout() {
        session('admin', null);
        session('admin_id', null);
        return true;
    }


}